# Generated by Django 5.2.4 on 2025-07-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firestore_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firestoreuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='firestorevideo',
            options={'managed': False},
        ),
    ]
