# Generated by Django 5.2.4 on 2025-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirestoreUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirestoreVideo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
